In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [3]:
dataset = pd.read_csv("7.1 Social_Network_Ads.csv")

In [4]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
x = dataset.iloc[:,[2,3]].values

In [7]:
y = dataset.iloc[:,4].values

In [8]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [11]:
from sklearn.cross_validation import train_test_split

ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [12]:
 from sklearn.cross_validation import train_test_split 

ModuleNotFoundError: No module named 'sklearn.cross_validation'

In [13]:
from sklearn.model_selection import train_test_split

In [15]:
X_train , X_test , Y_train , Y_test = train_test_split(x,y,test_size = 0.25)

In [16]:
X_train

array([[    38,  59000],
       [    44, 139000],
       [    60, 108000],
       [    24,  19000],
       [    35,  27000],
       [    37,  57000],
       [    24,  55000],
       [    32, 117000],
       [    46,  22000],
       [    33,  51000],
       [    38,  55000],
       [    54,  26000],
       [    26,  15000],
       [    41,  59000],
       [    29,  43000],
       [    60,  42000],
       [    30,  17000],
       [    59,  76000],
       [    35,  53000],
       [    46, 117000],
       [    31,  68000],
       [    42,  53000],
       [    36,  52000],
       [    25,  33000],
       [    40,  59000],
       [    31,  89000],
       [    47,  43000],
       [    31,  76000],
       [    19,  70000],
       [    48,  29000],
       [    33,  69000],
       [    22,  63000],
       [    42,  73000],
       [    36,  75000],
       [    50,  88000],
       [    58, 144000],
       [    36,  54000],
       [    39, 106000],
       [    59,  88000],
       [    39,  42000],


In [17]:
Y_train

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0], d

In [18]:
X_train.shape

(300, 2)

In [19]:
Y_train.shape

(300,)

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
sc = StandardScaler()

In [23]:
X_train = sc.fit_transform(X_train)

In [24]:
X_test = sc.transform(X_test)

In [25]:
X_train

array([[ 0.03082219, -0.28587417],
       [ 0.59694402,  2.04541368],
       [ 2.10660223,  1.14203964],
       [-1.29012874, -1.4515181 ],
       [-0.25223873, -1.21838932],
       [-0.06353145, -0.34415637],
       [-1.29012874, -0.40243857],
       [-0.53529964,  1.40430952],
       [ 0.78565129, -1.36409481],
       [-0.440946  , -0.51900296],
       [ 0.03082219, -0.40243857],
       [ 1.5404804 , -1.24753041],
       [-1.10142147, -1.56808249],
       [ 0.3138831 , -0.28587417],
       [-0.81836055, -0.75213174],
       [ 2.10660223, -0.78127284],
       [-0.72400692, -1.5098003 ],
       [ 2.01224859,  0.2095245 ],
       [-0.25223873, -0.46072076],
       [ 0.78565129,  1.40430952],
       [-0.62965328, -0.02360429],
       [ 0.40823674, -0.46072076],
       [-0.15788509, -0.48986186],
       [-1.19577511, -1.04354273],
       [ 0.21952946, -0.28587417],
       [-0.62965328,  0.58835877],
       [ 0.88000493, -0.75213174],
       [-0.62965328,  0.2095245 ],
       [-1.76189694,

In [26]:
X_test

array([[-1.6675433 , -1.33495371],
       [ 0.88000493,  1.28774513],
       [-1.38448238, -0.60642625],
       [-0.06353145,  0.32608889],
       [ 0.97435857, -0.81041394],
       [-0.25223873, -0.63556735],
       [ 0.69129765, -1.07268382],
       [-0.06353145,  0.1512423 ],
       [-0.25223873, -0.22759198],
       [ 1.35177312,  1.31688623],
       [ 1.44612676,  1.02547525],
       [ 0.03082219,  0.06381901],
       [-0.440946  ,  1.28774513],
       [ 1.5404804 ,  1.14203964],
       [-1.38448238,  0.38437109],
       [-0.62965328, -0.08188649],
       [-0.25223873,  0.29694779],
       [-0.72400692,  1.92884929],
       [-1.76189694,  0.2095245 ],
       [-1.38448238, -1.422377  ],
       [-0.25223873,  0.64664097],
       [ 0.21952946,  0.26780669],
       [ 1.5404804 ,  0.03467791],
       [ 0.78565129,  0.79234646],
       [ 0.12517583,  1.89970819],
       [ 0.3138831 ,  0.0929601 ],
       [ 1.35177312,  0.61749987],
       [-0.91271419, -0.28587417],
       [-0.440946  ,

In [27]:
from sklearn.neighbors import KNeighborsClassifier 

In [28]:
classifier = KNeighborsClassifier(n_neighbors = 5 , metric = 'minkowski')

In [30]:
classifier.fit(X_train , Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [31]:
Y_pred = classifier.predict(X_test)

In [32]:
Y_pred

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1], dtype=int64)

In [33]:
Y_test

array([0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1], dtype=int64)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
cm = confusion_matrix( Y_test , Y_pred)

In [36]:
cm

array([[55,  6],
       [ 4, 35]], dtype=int64)

In [37]:
(55 +35)/(55 + 6 + 4 +35)

0.9